#!/usr/bin/env python3
"""General program settings"""

#Window
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
WINDOW_RATIO = (WINDOW_WIDTH / WINDOW_HEIGHT)

#FPS Counter
FPS_OFFSET_X = 42
FPS_OFFSET_Y = 21
FPS_POS_X = (WINDOW_WIDTH - FPS_OFFSET_X)
FPS_POS_Y = (WINDOW_HEIGHT - FPS_OFFSET_Y)

#Terrain
TERRAIN_MAX_SIZE = 7
TERRAIN_GRID_PADDING = 2
TERRAIN_MAX_HEIGHT = 5
TERRAIN_MIN_HEIGHT = -5

#Color
COLOR_TERRAIN_HIGH = "#604020"
COLOR_TERRAIN_MID = "#206040"
COLOR_TERRAIN_LOW = "#333333"
COLOR_WATER = "#20406088"

COLOR_WINDOW = "#212121"
